apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: monitoring
spec:
  hosts:
    - "grafana.jacky3.com"
  gateways:
    - istio-system/monitoring-gateway
  http:
    - route:
        - destination:
            host: grafana.monitoring.svc.cluster.local
            port:
              number: 80
