apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-certs
  namespace: istio-system
spec:
  secretName: monitoring-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - jacky3.com
  - '*.jacky3.com'
