apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: monitoring-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress # 確保對應到你的 IngressGateway Pod
  servers:
  - hosts:
    - kiali.jacky3.com
    - grafana.jacky3.com
    - jaeger.jacky3.com
    - argocd.jacky3.com  # <--- 新增這一行
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true # 強制跳轉 HTTPS
  - hosts:
    - kiali.jacky3.com
    - grafana.jacky3.com
    - jaeger.jacky3.com
    - argocd.jacky3.com  # <--- 新增這一行
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: monitoring-certs # 確保這個 Secret 存在於 istio-system
      mode: SIMPLE
